//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomDolgov.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveSubstance> ActiveSubstance { get; set; }
        public virtual DbSet<BestBeforeDate> BestBeforeDate { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<ManufacturerCountry> ManufacturerCountry { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PrescriptionDrugStatus> PrescriptionDrugStatus { get; set; }
        public virtual DbSet<Realization> Realization { get; set; }
        public virtual DbSet<ReleaseForm> ReleaseForm { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StockUnit> StockUnit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMedicine> TypeMedicine { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
