//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomDolgov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Orders = new HashSet<Orders>();
            this.Realization = new HashSet<Realization>();
            this.StockUnit = new HashSet<StockUnit>();
        }
    
        public int IdMedicine { get; set; }
        public string NameMedicine { get; set; }
        public Nullable<int> IdTypeMedicine { get; set; }
        public Nullable<int> IdActiveSubstance { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<int> IdReleaseForm { get; set; }
        public decimal Dosage { get; set; }
        public Nullable<int> IdBestBeforeDate { get; set; }
        public int UnitsPerPackage { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> IdPrescriptionDrugStatus { get; set; }
        public byte[] MedicinePhoto { get; set; }
    
        public virtual ActiveSubstance ActiveSubstance { get; set; }
        public virtual BestBeforeDate BestBeforeDate { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual PrescriptionDrugStatus PrescriptionDrugStatus { get; set; }
        public virtual ReleaseForm ReleaseForm { get; set; }
        public virtual TypeMedicine TypeMedicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realization> Realization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockUnit> StockUnit { get; set; }
    }
}
