//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomDolgov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realization
    {
        public int IdRealization { get; set; }
        public Nullable<int> IdStaff { get; set; }
        public Nullable<int> IdGuest { get; set; }
        public System.DateTime DateTimeRealization { get; set; }
        public int IdMedicine { get; set; }
        public string Reason { get; set; }
        public int Count { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
